/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProjetsRouteImport } from './routes/projets'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DesignIndexRouteImport } from './routes/design/index'
import { Route as DesignOptionCRouteImport } from './routes/design/option-c'
import { Route as DesignOptionBRouteImport } from './routes/design/option-b'
import { Route as DesignOptionARouteImport } from './routes/design/option-a'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetsRoute = ProjetsRouteImport.update({
  id: '/projets',
  path: '/projets',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignIndexRoute = DesignIndexRouteImport.update({
  id: '/design/',
  path: '/design/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignOptionCRoute = DesignOptionCRouteImport.update({
  id: '/design/option-c',
  path: '/design/option-c',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignOptionBRoute = DesignOptionBRouteImport.update({
  id: '/design/option-b',
  path: '/design/option-b',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignOptionARoute = DesignOptionARouteImport.update({
  id: '/design/option-a',
  path: '/design/option-a',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/articles': typeof ArticlesRoute
  '/projets': typeof ProjetsRoute
  '/services': typeof ServicesRoute
  '/design/option-a': typeof DesignOptionARoute
  '/design/option-b': typeof DesignOptionBRoute
  '/design/option-c': typeof DesignOptionCRoute
  '/design': typeof DesignIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/articles': typeof ArticlesRoute
  '/projets': typeof ProjetsRoute
  '/services': typeof ServicesRoute
  '/design/option-a': typeof DesignOptionARoute
  '/design/option-b': typeof DesignOptionBRoute
  '/design/option-c': typeof DesignOptionCRoute
  '/design': typeof DesignIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/articles': typeof ArticlesRoute
  '/projets': typeof ProjetsRoute
  '/services': typeof ServicesRoute
  '/design/option-a': typeof DesignOptionARoute
  '/design/option-b': typeof DesignOptionBRoute
  '/design/option-c': typeof DesignOptionCRoute
  '/design/': typeof DesignIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/articles'
    | '/projets'
    | '/services'
    | '/design/option-a'
    | '/design/option-b'
    | '/design/option-c'
    | '/design'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/articles'
    | '/projets'
    | '/services'
    | '/design/option-a'
    | '/design/option-b'
    | '/design/option-c'
    | '/design'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/articles'
    | '/projets'
    | '/services'
    | '/design/option-a'
    | '/design/option-b'
    | '/design/option-c'
    | '/design/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArticlesRoute: typeof ArticlesRoute
  ProjetsRoute: typeof ProjetsRoute
  ServicesRoute: typeof ServicesRoute
  DesignOptionARoute: typeof DesignOptionARoute
  DesignOptionBRoute: typeof DesignOptionBRoute
  DesignOptionCRoute: typeof DesignOptionCRoute
  DesignIndexRoute: typeof DesignIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projets': {
      id: '/projets'
      path: '/projets'
      fullPath: '/projets'
      preLoaderRoute: typeof ProjetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/': {
      id: '/design/'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/option-c': {
      id: '/design/option-c'
      path: '/design/option-c'
      fullPath: '/design/option-c'
      preLoaderRoute: typeof DesignOptionCRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/option-b': {
      id: '/design/option-b'
      path: '/design/option-b'
      fullPath: '/design/option-b'
      preLoaderRoute: typeof DesignOptionBRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/option-a': {
      id: '/design/option-a'
      path: '/design/option-a'
      fullPath: '/design/option-a'
      preLoaderRoute: typeof DesignOptionARouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArticlesRoute: ArticlesRoute,
  ProjetsRoute: ProjetsRoute,
  ServicesRoute: ServicesRoute,
  DesignOptionARoute: DesignOptionARoute,
  DesignOptionBRoute: DesignOptionBRoute,
  DesignOptionCRoute: DesignOptionCRoute,
  DesignIndexRoute: DesignIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
